
[default]
dispatch.earliest_time = -30d
dispatch.latest_time = now

[Clop Ransomware Process Execution]
description = 
search = Image IN ("*CLOP.exe*", "*CLOP64.exe*", "*CLOP32.exe*")

[Clop Ransomware File Encryption Activity]
description = 
search = TargetFilename IN ("*.clop*", "*.encrypted*")
